// Generated by tools/build_standards.py from the Common Standards Project
// (https://commonstandardsproject.com). Do not edit by hand.
window.STANDARDS_INDEX = [
 {
  "name": "Common Core",
  "subjects": [
   {
    "name": "Mathematics",
    "docs": [
     {
      "id": "common-core-mathematics-kindergarten",
      "grade": "Kindergarten",
      "source": "Common Core State Standards for Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-mathematics-grade-1",
      "grade": "Grade 1",
      "source": "Common Core State Standards for Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-mathematics-grade-2",
      "grade": "Grade 2",
      "source": "Common Core State Standards for Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-mathematics-grade-3",
      "grade": "Grade 3",
      "source": "Common Core State Standards for Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-mathematics-grade-4",
      "grade": "Grade 4",
      "source": "Common Core State Standards for Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-mathematics-grade-5",
      "grade": "Grade 5",
      "source": "Common Core State Standards for Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-mathematics-grade-6",
      "grade": "Grade 6",
      "source": "Common Core State Standards for Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-mathematics-grade-7",
      "grade": "Grade 7",
      "source": "Common Core State Standards for Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-mathematics-grade-8",
      "grade": "Grade 8",
      "source": "Common Core State Standards for Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-mathematics-high-school",
      "grade": "High School",
      "source": "Common Core State Standards for Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     }
    ]
   },
   {
    "name": "English Language Arts",
    "docs": [
     {
      "id": "common-core-english-language-arts-kindergarten",
      "grade": "Kindergarten",
      "source": "Common Core State Standards for English Language Arts & Literacy in History/Social Studies, Science, and Technical Subjects",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-english-language-arts-grade-1",
      "grade": "Grade 1",
      "source": "Common Core State Standards for English Language Arts & Literacy in History/Social Studies, Science, and Technical Subjects",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-english-language-arts-grade-2",
      "grade": "Grade 2",
      "source": "Common Core State Standards for English Language Arts & Literacy in History/Social Studies, Science, and Technical Subjects",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-english-language-arts-grade-3",
      "grade": "Grade 3",
      "source": "Common Core State Standards for English Language Arts & Literacy in History/Social Studies, Science, and Technical Subjects",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-english-language-arts-grade-4",
      "grade": "Grade 4",
      "source": "Common Core State Standards for English Language Arts & Literacy in History/Social Studies, Science, and Technical Subjects",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-english-language-arts-grade-5",
      "grade": "Grade 5",
      "source": "Common Core State Standards for English Language Arts & Literacy in History/Social Studies, Science, and Technical Subjects",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-english-language-arts-grade-6",
      "grade": "Grade 6",
      "source": "Common Core State Standards for English Language Arts & Literacy in History/Social Studies, Science, and Technical Subjects",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-english-language-arts-grade-7",
      "grade": "Grade 7",
      "source": "Common Core State Standards for English Language Arts & Literacy in History/Social Studies, Science, and Technical Subjects",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-english-language-arts-grade-8",
      "grade": "Grade 8",
      "source": "Common Core State Standards for English Language Arts & Literacy in History/Social Studies, Science, and Technical Subjects",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-english-language-arts-grades-9-10",
      "grade": "Grades 9–10",
      "source": "Common Core State Standards for English Language Arts & Literacy in History/Social Studies, Science, and Technical Subjects",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "common-core-english-language-arts-grades-11-12",
      "grade": "Grades 11–12",
      "source": "Common Core State Standards for English Language Arts & Literacy in History/Social Studies, Science, and Technical Subjects",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     }
    ]
   }
  ]
 },
 {
  "name": "NGSS",
  "subjects": [
   {
    "name": "Science",
    "docs": [
     {
      "id": "ngss-science-kindergarten",
      "grade": "Kindergarten",
      "source": "Next Generation Science Standards",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ngss-science-grade-1",
      "grade": "Grade 1",
      "source": "Next Generation Science Standards",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ngss-science-grade-2",
      "grade": "Grade 2",
      "source": "Next Generation Science Standards",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ngss-science-grade-3",
      "grade": "Grade 3",
      "source": "Next Generation Science Standards",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ngss-science-grade-4",
      "grade": "Grade 4",
      "source": "Next Generation Science Standards",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ngss-science-grade-5",
      "grade": "Grade 5",
      "source": "Next Generation Science Standards",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ngss-science-grades-6-8",
      "grade": "Grades 6–8",
      "source": "Next Generation Science Standards",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ngss-science-high-school",
      "grade": "High School",
      "source": "Next Generation Science Standards",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     }
    ]
   }
  ]
 },
 {
  "name": "Ohio",
  "subjects": [
   {
    "name": "Mathematics",
    "docs": [
     {
      "id": "ohio-mathematics-kindergarten",
      "grade": "Kindergarten",
      "source": "Ohio Learning Standards: Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-mathematics-grade-1",
      "grade": "Grade 1",
      "source": "Ohio Learning Standards: Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-mathematics-grade-2",
      "grade": "Grade 2",
      "source": "Ohio Learning Standards: Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-mathematics-grade-3",
      "grade": "Grade 3",
      "source": "Ohio Learning Standards: Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-mathematics-grade-4",
      "grade": "Grade 4",
      "source": "Ohio Learning Standards: Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-mathematics-grade-5",
      "grade": "Grade 5",
      "source": "Ohio Learning Standards: Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-mathematics-grade-6",
      "grade": "Grade 6",
      "source": "Ohio Learning Standards: Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-mathematics-grade-7",
      "grade": "Grade 7",
      "source": "Ohio Learning Standards: Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-mathematics-grade-8",
      "grade": "Grade 8",
      "source": "Ohio Learning Standards: Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-mathematics-high-school",
      "grade": "High School",
      "source": "Ohio Learning Standards: Mathematics",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     }
    ]
   },
   {
    "name": "English Language Arts",
    "docs": [
     {
      "id": "ohio-english-language-arts-kindergarten",
      "grade": "Kindergarten",
      "source": "Ohio Learning Standards English Language Arts",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-english-language-arts-grade-1",
      "grade": "Grade 1",
      "source": "Ohio Learning Standards English Language Arts",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-english-language-arts-grade-2",
      "grade": "Grade 2",
      "source": "Ohio Learning Standards English Language Arts",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-english-language-arts-grade-3",
      "grade": "Grade 3",
      "source": "Ohio Learning Standards English Language Arts",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-english-language-arts-grade-4",
      "grade": "Grade 4",
      "source": "Ohio Learning Standards English Language Arts",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-english-language-arts-grade-5",
      "grade": "Grade 5",
      "source": "Ohio Learning Standards English Language Arts",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-english-language-arts-grade-6",
      "grade": "Grade 6",
      "source": "Ohio Learning Standards English Language Arts",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-english-language-arts-grade-7",
      "grade": "Grade 7",
      "source": "Ohio Learning Standards English Language Arts",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-english-language-arts-grade-8",
      "grade": "Grade 8",
      "source": "Ohio Learning Standards English Language Arts",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-english-language-arts-grades-9-10",
      "grade": "Grades 9–10",
      "source": "Ohio Learning Standards English Language Arts",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-english-language-arts-grades-11-12",
      "grade": "Grades 11–12",
      "source": "Ohio Learning Standards English Language Arts",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     }
    ]
   },
   {
    "name": "Science",
    "docs": [
     {
      "id": "ohio-science-kindergarten",
      "grade": "Kindergarten",
      "source": "Ohio Learning Standards: Science",
      "license": "",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-science-grade-1",
      "grade": "Grade 1",
      "source": "Ohio Learning Standards: Science",
      "license": "",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-science-grade-2",
      "grade": "Grade 2",
      "source": "Ohio Learning Standards: Science",
      "license": "",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-science-grade-3",
      "grade": "Grade 3",
      "source": "Ohio Learning Standards: Science",
      "license": "",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-science-grade-4",
      "grade": "Grade 4",
      "source": "Ohio Learning Standards: Science",
      "license": "",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-science-grade-5",
      "grade": "Grade 5",
      "source": "Ohio Learning Standards: Science",
      "license": "",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-science-grade-6",
      "grade": "Grade 6",
      "source": "Ohio Learning Standards: Science",
      "license": "",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-science-grade-7",
      "grade": "Grade 7",
      "source": "Ohio Learning Standards: Science",
      "license": "",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-science-grade-8",
      "grade": "Grade 8",
      "source": "Ohio Learning Standards: Science",
      "license": "",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-science-high-school-biology",
      "grade": "High School — Biology",
      "source": "Ohio Learning Standards: Science",
      "license": "",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-science-high-school-chemistry",
      "grade": "High School — Chemistry",
      "source": "Ohio Learning Standards: Science",
      "license": "",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-science-high-school-environmental-science",
      "grade": "High School — Environmental Science",
      "source": "Ohio Learning Standards: Science",
      "license": "",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-science-high-school-human-anatomy-and-physiology",
      "grade": "High School — Human Anatomy and Physiology",
      "source": "Ohio Learning Standards: Science",
      "license": "",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-science-high-school-physical-geology",
      "grade": "High School — Physical Geology",
      "source": "Ohio Learning Standards: Science",
      "license": "",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-science-high-school-physical-science",
      "grade": "High School — Physical Science",
      "source": "Ohio Learning Standards: Science",
      "license": "",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-science-high-school-physics",
      "grade": "High School — Physics",
      "source": "Ohio Learning Standards: Science",
      "license": "",
      "rightsHolder": "D2L Corporation"
     }
    ]
   },
   {
    "name": "Social Studies",
    "docs": [
     {
      "id": "ohio-social-studies-kindergarten",
      "grade": "Kindergarten",
      "source": "Ohio's Learning Standards Social Studies",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-social-studies-grade-1",
      "grade": "Grade 1",
      "source": "Ohio's Learning Standards Social Studies",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-social-studies-grade-2",
      "grade": "Grade 2",
      "source": "Ohio's Learning Standards Social Studies",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-social-studies-grade-3",
      "grade": "Grade 3",
      "source": "Ohio's Learning Standards Social Studies",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-social-studies-grade-4",
      "grade": "Grade 4",
      "source": "Ohio's Learning Standards Social Studies",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-social-studies-grade-5",
      "grade": "Grade 5",
      "source": "Ohio's Learning Standards Social Studies",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-social-studies-grade-6",
      "grade": "Grade 6",
      "source": "Ohio's Learning Standards Social Studies",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-social-studies-grade-7",
      "grade": "Grade 7",
      "source": "Ohio's Learning Standards Social Studies",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-social-studies-grade-8",
      "grade": "Grade 8",
      "source": "Ohio's Learning Standards Social Studies",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     },
     {
      "id": "ohio-social-studies-high-school",
      "grade": "High School",
      "source": "Ohio's Learning Standards Social Studies",
      "license": "CC BY 3.0 US",
      "rightsHolder": "D2L Corporation"
     }
    ]
   },
   {
    "name": "Computer Science",
    "docs": [
     {
      "id": "ohio-computer-science-kindergarten",
      "grade": "Kindergarten",
      "source": "Ohio’s Learning Standards Computer Science ADOPTED JULY 2022",
      "license": "CC BY 4.0 US",
      "rightsHolder": "Common Curriculum, Inc."
     },
     {
      "id": "ohio-computer-science-grade-1",
      "grade": "Grade 1",
      "source": "Ohio’s Learning Standards Computer Science ADOPTED JULY 2022",
      "license": "CC BY 4.0 US",
      "rightsHolder": "Common Curriculum, Inc."
     },
     {
      "id": "ohio-computer-science-grade-2",
      "grade": "Grade 2",
      "source": "Ohio’s Learning Standards Computer Science",
      "license": "CC BY 4.0 US",
      "rightsHolder": "Common Curriculum, Inc."
     },
     {
      "id": "ohio-computer-science-grade-3",
      "grade": "Grade 3",
      "source": "Ohio’s Learning Standards Computer Science ADOPTED JULY 2022",
      "license": "CC BY 4.0 US",
      "rightsHolder": "Common Curriculum, Inc."
     },
     {
      "id": "ohio-computer-science-grade-4",
      "grade": "Grade 4",
      "source": "Ohio’s Learning Standards Computer Science ADOPTED JULY 2022",
      "license": "CC BY 4.0 US",
      "rightsHolder": "Common Curriculum, Inc."
     },
     {
      "id": "ohio-computer-science-grade-5",
      "grade": "Grade 5",
      "source": "Ohio’s Learning Standards Computer Science ADOPTED JULY 2022",
      "license": "CC BY 4.0 US",
      "rightsHolder": "Common Curriculum, Inc."
     },
     {
      "id": "ohio-computer-science-grade-6",
      "grade": "Grade 6",
      "source": "Ohio’s Learning Standards Computer Science ADOPTED JULY 2022",
      "license": "CC BY 4.0 US",
      "rightsHolder": "Common Curriculum, Inc."
     },
     {
      "id": "ohio-computer-science-grade-7",
      "grade": "Grade 7",
      "source": "Ohio’s Learning Standards Computer Science ADOPTED JULY 2022",
      "license": "CC BY 4.0 US",
      "rightsHolder": "Common Curriculum, Inc."
     },
     {
      "id": "ohio-computer-science-grade-8",
      "grade": "Grade 8",
      "source": "Ohio’s Learning Standards Computer Science ADOPTED JULY 2022",
      "license": "CC BY 4.0 US",
      "rightsHolder": "Common Curriculum, Inc."
     },
     {
      "id": "ohio-computer-science-high-school-advanced",
      "grade": "High School — Advanced",
      "source": "Ohio’s Learning Standards Computer Science ADOPTED JULY 2022",
      "license": "CC BY 4.0 US",
      "rightsHolder": "Common Curriculum, Inc."
     },
     {
      "id": "ohio-computer-science-high-school-foundational",
      "grade": "High School — Foundational",
      "source": "Ohio’s Learning Standards Computer Science ADOPTED JULY 2022",
      "license": "CC BY 4.0 US",
      "rightsHolder": "Common Curriculum, Inc."
     }
    ]
   }
  ]
 },
 {
  "name": "CSTA",
  "subjects": [
   {
    "name": "Computer Science",
    "docs": [
     {
      "id": "csta-computer-science-grades-k-2-level-1a",
      "grade": "Grades K–2 (Level 1A)",
      "source": "K-12 Computer Science Standards Revised 2017",
      "license": "CC BY 4.0 US",
      "rightsHolder": "Common Curriculum, Inc."
     },
     {
      "id": "csta-computer-science-grades-3-5-level-1b",
      "grade": "Grades 3–5 (Level 1B)",
      "source": "K-12 Computer Science Standards Revised 2017",
      "license": "CC BY 4.0 US",
      "rightsHolder": "Common Curriculum, Inc."
     },
     {
      "id": "csta-computer-science-grades-6-8-level-2",
      "grade": "Grades 6–8 (Level 2)",
      "source": "K-12 Computer Science Standards Revised 2017",
      "license": "CC BY 4.0 US",
      "rightsHolder": "Common Curriculum, Inc."
     },
     {
      "id": "csta-computer-science-grades-9-10-level-3a",
      "grade": "Grades 9–10 (Level 3A)",
      "source": "K-12 Computer Science Standards Revised 2017",
      "license": "CC BY 4.0 US",
      "rightsHolder": "Common Curriculum, Inc."
     },
     {
      "id": "csta-computer-science-grades-11-12-level-3b",
      "grade": "Grades 11–12 (Level 3B)",
      "source": "K-12 Computer Science Standards Revised 2017",
      "license": "CC BY 4.0 US",
      "rightsHolder": "Common Curriculum, Inc."
     }
    ]
   }
  ]
 }
];
