// Teacher-made puzzles, each tied to one standards document and the standards it covers.
// Add entries with the builder's "Copy library entry" button (open index.html#puzzle-builder).
// Fields: t = title, doc = standards document id, codes = standard codes, seed = layout, w = [WORD, clue] pairs.
window.PUZZLE_LIBRARY = [
  { seed: 1, t: 'Geometry & Scale Drawings', doc: 'common-core-mathematics-grade-7', codes: ['CCSS.Math.Content.7.G.A.1'], w: [
    ['SCALE', "Ratio comparing a drawing's dimensions to actual size"],
    ['RADIUS', 'Distance from the center of a circle to any point on it'],
    ['DIAMETER', "Segment through a circle's center, end to end"],
    ['AREA', 'Amount of 2D space inside a closed shape'],
    ['PERIMETER', 'Total distance around the outside of a shape'],
    ['RATIO', 'Quantitative relationship between two numbers'],
    ['ANGLE', 'Figure formed by two rays sharing a vertex'],
    ['PROPORTION', 'Equation stating that two ratios are equal'],
    ['SIMILAR', 'Having equal angles and proportional sides'],
  ]},
  { seed: 1, t: 'Equations & Exponents', doc: 'ohio-mathematics-grade-8', codes: ['8.EE.1'], w: [
    ['EXPONENT', 'Power to which a base is raised'],
    ['VARIABLE', 'Symbol standing for an unknown value'],
    ['EQUATION', 'Statement that two expressions are equal'],
    ['SLOPE', 'Steepness of a line: rise over run'],
    ['LINEAR', 'Kind of equation whose graph is a straight line'],
    ['COEFFICIENT', 'Number multiplied by a variable in a term'],
    ['RADICAL', 'Symbol for a square root or higher root'],
    ['FUNCTION', 'Rule assigning exactly one output to each input'],
  ]},
  { seed: 1, t: 'Cell Systems', doc: 'ngss-science-grades-6-8', codes: ['MS-LS1-1'], w: [
    ['MITOCHONDRIA', 'Organelle that produces cellular energy (ATP)'],
    ['NUCLEUS', "Cell's control center, home of its DNA"],
    ['MEMBRANE', 'Selective barrier around a cell'],
    ['CYTOPLASM', 'Jelly-like fluid filling a cell'],
    ['RIBOSOME', 'Where proteins are made'],
    ['ORGANELLE', 'Specialized structure within a cell'],
    ['CHLOROPLAST', 'Site of photosynthesis in plant cells'],
    ['DIFFUSION', 'Movement from higher to lower concentration'],
    ['VACUOLE', 'Storage compartment for water and nutrients'],
  ]},
  { seed: 1, t: 'Earth Systems', doc: 'ohio-science-grade-8', codes: ['8.ESS.1', '8.ESS.2', '8.ESS.3'], w: [
    ['MAGMA', "Molten rock beneath Earth's surface"],
    ['TECTONIC', "Kind of plate that forms Earth's outer shell"],
    ['SEDIMENT', 'Material deposited by water, wind, or ice'],
    ['EROSION', 'Wearing away and carrying off of rock or soil'],
    ['CRUST', "Earth's outermost solid shell"],
    ['MANTLE', 'Layer of hot, semi-solid rock beneath the crust'],
    ['FOSSIL', 'Preserved trace of an ancient organism'],
  ]},
  { seed: 1, t: 'Literary Craft', doc: 'common-core-english-language-arts-grades-9-10', codes: ['CCSS.ELA-Literacy.RL.9-10.4'], w: [
    ['METAPHOR', 'Comparison without "like" or "as"'],
    ['ALLITERATION', 'Repeated initial consonant sounds'],
    ['THEME', 'Central message of a literary work'],
    ['IRONY', 'Gap between expectation and outcome'],
    ['SYMBOLISM', 'Objects standing for abstract ideas'],
    ['STANZA', 'Group of lines in a poem'],
    ['PROTAGONIST', 'Main character of a story'],
    ['FORESHADOW', 'Hint at events to come'],
  ]},
  { seed: 1, t: 'American Government', doc: 'ohio-social-studies-high-school', codes: ['9-12.AG.5', '9-12.AG.7', '9-12.AG.10'], w: [
    ['CONSTITUTION', 'Supreme law establishing the federal government'],
    ['AMENDMENT', 'Formal change to the constitution'],
    ['JUDICIAL', 'Branch that interprets the laws'],
    ['CONGRESS', 'Bicameral federal legislature'],
    ['DEMOCRACY', 'Government by the people'],
    ['VETO', "Executive's rejection of a bill"],
    ['SUFFRAGE', 'The right to vote'],
  ]},
  { seed: 1, t: 'Algorithms', doc: 'csta-computer-science-grades-9-10-level-3a', codes: ['3A-AP-13'], w: [
    ['ALGORITHM', 'Step-by-step procedure for solving a problem'],
    ['VARIABLE', 'Named storage location holding a value'],
    ['BOOLEAN', 'Data type that is either true or false'],
    ['RECURSION', 'A function calling itself'],
    ['COMPILER', 'Translates source code to machine code'],
    ['BINARY', 'Base-2 number system'],
    ['ITERATION', 'One pass through a loop'],
  ]},
];
